In [1]:
%load_ext autoreload
%autoreload 2
import submission_test

In [2]:
# Write two classes, observation and configuration, in order for the script to run.
import random
import numpy as np

class Observation():
    def __init__(self):
        self.step = 0
        self.lastOpponentAction = None
        
    def update(self, this_step):
        self.lastOpponentAction = this_step
        self.step += 1  
        
class Configuration():
    def __init__(self):
        self.episodeSteps = 1000
        self.signs = 3

In [3]:
# Test script.

obs = Observation()
conf = Configuration()

for n in range(1000):
    submission_test.main(obs, conf)
    obs.update(np.random.randint(3))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 2 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 2 1 0 1 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 2 1 0 2 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 2 1 0 2 0 1 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 2 1 0 2 0 2 0]
[0 0 1 0 0 0 1 0 0 0 0 0 0 2 1 0 2 0 2 0]
[0 0 1 0 0 0 1 0 0 0 0 0 0 2 1 0 3 0 2 0]
[0 0 2 0 0 0 1 0 0 0 0 0 0 2 1 0 3 0 2 0]
[0 0 3 0 0 0 1 0 0 0 0 0 0 2 1 0 3 0 2 0]
[0 0 3 0 0 0 1 0 0 0 0 0 0 2 2 0 3 0 2 0]
[0 0 3 0 0 0 1 0 0 0 0 0 0 2 3 0 3 0 2 0]
[0 0 3 0 0 0 1 0 0 0 0 0 0 2 3 0 4 0 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 0 2 3 0 4 0 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 0 2 3 0 4 1 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 0 2 3 0 5 1 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 1 2 3 0 5 1 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 1 2 3 0 6 1 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 1 2 3 0 7 1 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 1 2 3 0 7 2 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 1 2 3 0 8 2 2 0]
[0 0 4 0 0 0 1 0 0 0 0 0 1 2 3 0 9

[ 6 15 11  9  4  3  7  8  5  2  8  0  2  9  7  2 13 21  8  3]
[ 6 15 11  9  4  3  7  8  5  2  8  0  3  9  7  2 13 21  8  3]
[ 6 15 11  9  4  4  7  8  5  2  8  0  3  9  7  2 13 21  8  3]
[ 6 15 11  9  4  4  7  8  5  2  8  0  4  9  7  2 13 21  8  3]
[ 6 15 11  9  4  4  7  8  5  2  8  0  4  9  7  3 13 21  8  3]
[ 6 15 11  9  4  4  7  8  5  2  8  0  5  9  7  3 13 21  8  3]
[ 6 15 11  9  4  4  7  8  5  2  8  0  6  9  7  3 13 21  8  3]
[ 6 15 11  9  4  4  7  8  5  2  8  0  6  9  7  4 13 21  8  3]
[ 6 15 11  9  4  4  7  8  5  2  8  0  7  9  7  4 13 21  8  3]
[ 6 15 11  9  4  4  7  9  5  2  8  0  7  9  7  4 13 21  8  3]
[ 6 15 11  9  4  4  7  9  5  2  8  1  7  9  7  4 13 21  8  3]
[ 6 15 11  9  4  4  7  9  5  2  8  1  7 10  7  4 13 21  8  3]
[ 6 15 11  9  4  4  7 10  5  2  8  1  7 10  7  4 13 21  8  3]
[ 6 15 11  9  4  4  7 10  5  2  8  2  7 10  7  4 13 21  8  3]
[ 6 15 11  9  4  4  7 10  5  2  8  2  7 10  8  4 13 21  8  3]
[ 6 15 11  9  4  4  7 10  5  2  8  2  7 10  9  4 13 21  8  3]
[ 6 15 1

[10 21 15 14 15 10  9 14 14 12 12 22 10 13 10 13 16 29 13  6]
[10 21 15 14 15 10  9 14 14 12 12 22 10 13 10 13 17 29 13  6]
[10 21 15 14 16 10  9 14 14 12 12 22 10 13 10 13 17 29 13  6]
[10 21 15 14 16 10  9 14 14 12 13 22 10 13 10 13 17 29 13  6]
[10 22 15 14 16 10  9 14 14 12 13 22 10 13 10 13 17 29 13  6]
[10 23 15 14 16 10  9 14 14 12 13 22 10 13 10 13 17 29 13  6]
[10 23 15 15 16 10  9 14 14 12 13 22 10 13 10 13 17 29 13  6]
[10 23 15 15 16 10  9 14 14 12 13 22 11 13 10 13 17 29 13  6]
[10 23 15 15 16 10  9 14 14 12 13 22 11 13 10 13 17 29 14  6]
[10 23 15 15 16 10  9 14 15 12 13 22 11 13 10 13 17 29 14  6]
[10 23 15 15 16 10  9 14 16 12 13 22 11 13 10 13 17 29 14  6]
[10 23 15 15 16 10  9 14 17 12 13 22 11 13 10 13 17 29 14  6]
[10 23 15 15 16 10  9 14 18 12 13 22 11 13 10 13 17 29 14  6]
[10 23 15 16 16 10  9 14 18 12 13 22 11 13 10 13 17 29 14  6]
[10 23 15 16 16 10  9 14 19 12 13 22 11 13 10 13 17 29 14  6]
[10 23 15 16 16 10  9 14 20 12 13 22 11 13 10 13 17 29 14  6]
[10 23 1

[15 26 18 17 23 17 13 28 28 14 15 38 16 15 11 14 23 35 29 17]
[15 26 18 17 23 17 13 28 28 14 15 38 16 16 11 14 23 35 29 17]
[15 26 18 17 23 17 13 28 28 14 15 38 16 16 12 14 23 35 29 17]
[15 26 18 17 23 17 13 29 28 14 15 38 16 16 12 14 23 35 29 17]
[15 26 18 17 23 17 13 29 28 14 15 39 16 16 12 14 23 35 29 17]
[15 26 18 17 23 17 13 29 28 14 15 39 16 17 12 14 23 35 29 17]
[15 26 18 17 23 17 14 29 28 14 15 39 16 17 12 14 23 35 29 17]
[15 26 18 17 23 17 15 29 28 14 15 39 16 17 12 14 23 35 29 17]
[15 26 18 17 23 17 16 29 28 14 15 39 16 17 12 14 23 35 29 17]
[15 26 18 17 23 17 16 29 28 14 15 40 16 17 12 14 23 35 29 17]
[15 26 18 17 23 17 16 29 28 14 15 40 16 17 12 14 23 35 29 18]
[15 26 18 17 23 17 17 29 28 14 15 40 16 17 12 14 23 35 29 18]
[15 26 18 17 23 17 17 29 28 14 15 40 16 17 12 14 23 35 29 19]
[15 26 18 17 23 17 17 29 28 14 15 40 17 17 12 14 23 35 29 19]
[15 26 18 17 23 17 17 29 28 14 15 40 17 17 12 14 23 35 29 20]
[15 26 18 17 23 17 17 29 28 14 15 41 17 17 12 14 23 35 29 20]
[15 26 1

[24 31 34 23 23 20 24 32 29 21 22 46 17 27 14 17 40 39 31 31]
[24 31 35 23 23 20 24 32 29 21 22 46 17 27 14 17 40 39 31 31]
[24 32 35 23 23 20 24 32 29 21 22 46 17 27 14 17 40 39 31 31]
[24 32 35 23 23 20 24 32 29 21 22 46 17 27 14 17 40 40 31 31]
[24 33 35 23 23 20 24 32 29 21 22 46 17 27 14 17 40 40 31 31]
[24 33 35 23 23 21 24 32 29 21 22 46 17 27 14 17 40 40 31 31]
[24 33 36 23 23 21 24 32 29 21 22 46 17 27 14 17 40 40 31 31]
[24 33 36 23 23 21 24 32 29 21 22 46 17 27 14 17 41 40 31 31]
[24 33 36 23 23 21 24 32 29 21 22 46 17 27 14 17 42 40 31 31]
[24 33 36 23 23 21 24 32 29 22 22 46 17 27 14 17 42 40 31 31]
[24 33 36 23 23 21 25 32 29 22 22 46 17 27 14 17 42 40 31 31]
[24 33 36 23 23 21 26 32 29 22 22 46 17 27 14 17 42 40 31 31]
[24 33 37 23 23 21 26 32 29 22 22 46 17 27 14 17 42 40 31 31]
[24 33 37 23 23 21 27 32 29 22 22 46 17 27 14 17 42 40 31 31]
[24 33 37 24 23 21 27 32 29 22 22 46 17 27 14 17 42 40 31 31]
[24 33 37 24 23 21 27 32 29 23 22 46 17 27 14 17 42 40 31 31]
[24 33 3

[37 40 40 25 23 23 35 47 42 30 27 47 26 28 20 20 50 42 36 40]
[37 40 40 25 23 23 35 47 42 30 27 47 26 28 20 21 50 42 36 40]
[37 40 40 25 23 23 35 47 42 30 27 47 26 28 20 21 50 42 36 41]
[37 41 40 25 23 23 35 47 42 30 27 47 26 28 20 21 50 42 36 41]
[37 42 40 25 23 23 35 47 42 30 27 47 26 28 20 21 50 42 36 41]
[37 42 40 25 23 23 35 47 43 30 27 47 26 28 20 21 50 42 36 41]
[37 42 40 25 23 24 35 47 43 30 27 47 26 28 20 21 50 42 36 41]
[37 42 40 25 23 24 35 47 43 30 27 47 26 28 21 21 50 42 36 41]
[37 42 40 25 23 24 35 47 43 30 27 47 26 28 22 21 50 42 36 41]
[37 42 40 25 23 24 35 47 43 30 27 47 27 28 22 21 50 42 36 41]
[37 42 40 25 23 24 35 47 43 30 27 47 27 28 22 21 50 43 36 41]
[37 42 40 25 23 24 35 47 43 30 27 48 27 28 22 21 50 43 36 41]
[37 42 40 25 23 24 35 47 43 30 27 48 27 28 23 21 50 43 36 41]
[37 42 40 25 23 24 35 47 43 30 28 48 27 28 23 21 50 43 36 41]
[37 42 40 25 23 24 35 47 43 30 28 49 27 28 23 21 50 43 36 41]
[37 42 40 25 23 24 35 47 44 30 28 49 27 28 23 21 50 43 36 41]
[37 42 4

[40 47 45 36 25 25 40 49 74 33 38 52 31 34 26 26 60 47 36 47]
[40 47 45 36 26 25 40 49 74 33 38 52 31 34 26 26 60 47 36 47]
[40 47 45 36 26 25 40 49 74 33 38 52 31 35 26 26 60 47 36 47]
[40 47 45 36 26 25 40 49 74 33 38 52 31 36 26 26 60 47 36 47]
[40 47 45 36 26 25 40 49 74 33 39 52 31 36 26 26 60 47 36 47]
[40 47 45 36 26 25 40 49 75 33 39 52 31 36 26 26 60 47 36 47]
[40 47 45 36 26 25 40 49 75 33 39 52 31 37 26 26 60 47 36 47]
[40 47 45 36 26 25 40 49 75 33 39 52 31 38 26 26 60 47 36 47]
[40 47 45 36 26 25 41 49 75 33 39 52 31 38 26 26 60 47 36 47]
[41 47 45 36 26 25 41 49 75 33 39 52 31 38 26 26 60 47 36 47]
[41 47 45 36 26 25 41 49 75 33 39 52 31 39 26 26 60 47 36 47]
[41 47 45 36 26 25 41 49 76 33 39 52 31 39 26 26 60 47 36 47]
[41 48 45 36 26 25 41 49 76 33 39 52 31 39 26 26 60 47 36 47]
[41 48 45 36 26 25 42 49 76 33 39 52 31 39 26 26 60 47 36 47]
[41 48 45 37 26 25 42 49 76 33 39 52 31 39 26 26 60 47 36 47]
[41 48 45 38 26 25 42 49 76 33 39 52 31 39 26 26 60 47 36 47]
[41 48 4

[41 51 49 51 27 27 48 58 76 47 48 52 35 47 27 27 73 56 52 53]
[41 51 49 51 27 28 48 58 76 47 48 52 35 47 27 27 73 56 52 53]
[41 51 49 51 27 28 48 58 76 47 49 52 35 47 27 27 73 56 52 53]
[41 51 49 51 28 28 48 58 76 47 49 52 35 47 27 27 73 56 52 53]
[41 51 49 51 28 28 48 59 76 47 49 52 35 47 27 27 73 56 52 53]
[41 51 49 51 28 28 48 59 76 48 49 52 35 47 27 27 73 56 52 53]
[41 51 49 51 29 28 48 59 76 48 49 52 35 47 27 27 73 56 52 53]
[41 51 49 51 29 28 48 59 76 48 50 52 35 47 27 27 73 56 52 53]
[41 51 49 51 29 28 48 59 76 48 51 52 35 47 27 27 73 56 52 53]
[41 51 49 52 29 28 48 59 76 48 51 52 35 47 27 27 73 56 52 53]
[41 51 49 52 29 28 48 60 76 48 51 52 35 47 27 27 73 56 52 53]
[41 51 49 52 29 28 48 60 76 48 52 52 35 47 27 27 73 56 52 53]
[41 51 49 52 29 28 48 61 76 48 52 52 35 47 27 27 73 56 52 53]
[41 51 49 52 29 28 48 61 76 48 53 52 35 47 27 27 73 56 52 53]
[41 51 49 52 29 28 49 61 76 48 53 52 35 47 27 27 73 56 52 53]
[41 51 49 52 29 28 49 62 76 48 53 52 35 47 27 27 73 56 52 53]
[41 51 4